# Generated by Django 5.2.17 on 2026-09-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["due_date", "name"]},
        ),
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ChoreAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("chore", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="chores.chore")),
                ("assignee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="chores.householdmember")),
            ],
            options={"ordering": ["-assigned_at"]},
        ),
    ]
